baseURL = 'https://jakeytts.com/'
languageCode = 'en-us'
title = 'JakeyTTS'
enableEmoji = true

[module]
  [[module.imports]]
    path = "github.com/colinwilson/lotusdocs"
  [[module.imports]]
    path = "github.com/fauzanmy/pehtheme-hugo"

[params]
  description = "JakeyTTS is a powerful, lightweight Text-to-Speech (TTS) client designed for streamers and creators. It features Twitch integration, custom voice mixing, sound effects (SFX), musical melodies, and an extensible plugin system."
  version = "2.0"
  # Enable dark mode
  darkMode = true
  # Disable search if not configured
  # search = false

[params.social]
  github = "JakeyTTS/JakeyTTS"
  discord = "yk25Vg4Ju8"

[params.docs]
  darkMode = true
  sidebarIcons = true

[params.flexsearch]
  enabled = true

[params.footer]
  copyright = "Copyright &copy; JakeyTTS 2026"

[[menu.primary]]
  name = "Documentation"
  url = "/docs/"
  weight = 10

[[menu.primary]]
  name = "Blog"
  url = "/blog/"
  weight = 20

[params.Author]
  name = "abdldavid"
  bio = "The creator and maintainer of JakeyTTS, a powerful text-to-speech engine for streamers."
  avatar = "images/logo.png"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 10

[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 20

[[menu.main]]
  name = "Documentation"
  url = "/docs/"
  weight = 30

[outputs]
  home = ["HTML", "JSON"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]

[permalinks]
  tags = "/blog/tags/:slug/"

[markup]
    [markup.tableOfContents]
      endLevel = 3
      startLevel = 1
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # https://jdhao.github.io/2019/12/29/hugo_html_not_shown/
  [markup.goldmark.parser]
    [markup.goldmark.parser.attribute]
      block = true